### ISSUE TITLE
Error when registering - verification - first step

### ISSUE THREAD

**Issue by felesmortis** [kestasjk/webDiplomacy#277]
`trying to register: SMTP server error: 5.4.5 Daily user sending quota exceeded. k18sm15757400eda.20 - gsmtp`

This occurs when registering.
Desktop and mobile.
Multiple emails and browsers tested.

Looks like your mail service may need to be upgraded.

**Comment by TimothyJones** [comment]
Thanks, I'll forward this on to the site admins (this issue tracker is for the code).

I know it's frustrating, but a workaround is to wait until tomorrow.

**Comment by TimothyJones** [comment]
Update: Should be fixed now.

**Comment by silentcoder99** [comment]
Hi, so I just tried to create an account yesterday and got the same error, looks like this is still an issue.

**Comment by j2l** [comment]
👍
